### ISSUE TITLE
Requiring packages that use relative imports fail

### ISSUE THREAD

**Issue by jampekka** [nodepy/nodepy#22]
I'm not exactly sure if this is desired behavior or not, but trying to `require` a package that uses relative imports fails. Eg if I have a layout described below, running `python2 ./test.py` works fine, but `nodepy2 ./test.py` fails with `ImportError: No module named sibling`.

As I said, I'm not sure if this is the intended behavior, but if it is, I think there should be some kind of method to import modules that use "traditional" python imports.

`./test.py`:
```python
def is_nodepy():
    try:
        require
        return True
    except NameError:
        return False

if is_nodepy():
    nesting = require('nesting', exports=False)
else:
    sys.path.append('./nodepy_modules/')
    import nesting

print(nesting.VALUE)
```

`./nodepy_modules/nesting/__init__.py`:
```python
import sibling
VALUE = sibling.VALUE
```

`./nodepy_modules/nesting/sibling.py`:
```python
VALUE = 'just a value'
```

PS. This is exactly the kind of package manager Python needs!

**Comment by NiklasRosenstein** [comment]
Hi @jampekka 

I am sorry for the late reply! Somehow I completely missed the notifications for this issue.

This is intended behaviour. If you want to use standard Python modules, you will also have to `import` them the Python way. Thus, whether you're in Node.Py or just standard Python, just do `import nesting`. 

While you may be able to create a Python module that works fine with Node.Py and standard Python, at the time the module is installed, it should be clear as what the module is used. I.e. if the module lies in `nodepy_modules/`, it's a Node.Py module that can be `require()`d. If the module lies somewhere in `sys.path` or `nodepy_modules/.pip/Lib/site-packages` (or the respectively correct path for your OS), it is a Python module that can be `import`ed.

Hope that helps!

> PS. This is exactly the kind of package manager Python needs!

I appreciate that you think the same! :grin:

**Comment by NiklasRosenstein** [comment]
I'll assume that your question has been answered. :)
