### ISSUE TITLE
Cannot install nodepy-pm

### ISSUE THREAD

**Issue by rsodre** [nodepy/nodepy#72]
Hey!

I can't install nodepy-pm on macOS 10.12.6.
None of the install options work...

```
$ python --version
Python 2.7.14

$ pip install node.py
Requirement already satisfied: node.py in /usr/local/lib/python2.7/site-packages
Requirement already satisfied: colorama>=0.3.9 in /usr/local/lib/python2.7/site-packages (from node.py)
Requirement already satisfied: localimport>=1.5.1 in /usr/local/lib/python2.7/site-packages (from node.py)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python2.7/site-packages (from node.py)
Requirement already satisfied: pip>=8.0.0 in /usr/local/lib/python2.7/site-packages (from node.py)
Requirement already satisfied: wheel>=0.29.0 in /usr/local/lib/python2.7/site-packages (from node.py)

$ nodepy https://nodepy.org/install-pm.py 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nodepy.py", line 1982, in _main
    exports=False, loader=loader)
  File "/usr/local/lib/python2.7/site-packages/nodepy.py", line 1232, in __call__
    additional_path=self.path, is_main=is_main, exec_=exec_, cache=cache)
  File "/usr/local/lib/python2.7/site-packages/nodepy.py", line 1673, in resolve_and_load
    return self.load_module(self.resolve(request), request, exec_=exec_)
  File "/usr/local/lib/python2.7/site-packages/nodepy.py", line 1593, in resolve
    raise ResolveError(request)
ResolveError: 'https://nodepy.org/install-pm.py' [main] (from directory '.') searched in:
  - 'nodepy_modules'

$ nodepy https://raw.githubusercontent.com/nodepy/nodepy-pm/master/scripts/install-remote.py
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nodepy.py", line 1982, in _main
    exports=False, loader=loader)
  File "/usr/local/lib/python2.7/site-packages/nodepy.py", line 1232, in __call__
    additional_path=self.path, is_main=is_main, exec_=exec_, cache=cache)
  File "/usr/local/lib/python2.7/site-packages/nodepy.py", line 1673, in resolve_and_load
    return self.load_module(self.resolve(request), request, exec_=exec_)
  File "/usr/local/lib/python2.7/site-packages/nodepy.py", line 1593, in resolve
    raise ResolveError(request)
ResolveError: 'https://raw.githubusercontent.com/nodepy/nodepy-pm/master/scripts/install-remote.py' [main] (from directory '.') searched in:
  - 'nodepy_modules'

$ nodepy nodepy-pm/scripts/install.py
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nodepy.py", line 747, in exec_
    py_compile.compile(tmp.name, cfile=bytecache_file, dfile=filename, doraise=True)
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/py_compile.py", line 117, in compile
    raise py_exc
PyCompileError:   File "/Users/roger/Dev/nodepy/nodepy-pm/scripts/install.py", line 21
    import brewfix from '../lib/brewfix'
                      ^
SyntaxError: invalid syntax

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nodepy.py", line 1986, in _main
    module.exec_()
  File "/usr/local/lib/python2.7/site-packages/nodepy.py", line 866, in exec_
    self.loader.exec_(self)
  File "/usr/local/lib/python2.7/site-packages/nodepy.py", line 772, in exec_
    code, extensions = self.load_code(context, package, filename, is_compiled=None)
  File "/usr/local/lib/python2.7/site-packages/nodepy.py", line 842, in load_code
    return compile(source, filename, 'exec', dont_inherit=True), extensions
  File "/Users/roger/Dev/nodepy/nodepy-pm/scripts/install.py", line 21
    import brewfix from '../lib/brewfix'
                      ^
SyntaxError: invalid syntax

```

**Comment by NiklasRosenstein** [comment]
Hi! Today Node.py 2 was release, which is installed via Pip using `pip install nodepy-runtime` instead of `pip install node.py`. Please try again and let me know if it works.

**Comment by NiklasRosenstein** [comment]
I also just noticed that you have `node.py` still installed, so please uninstall it first with

    pip uninstall node.py

**Comment by rsodre** [comment]
Hi @NiklasRosenstein.
I'm installing for c4ddev. Is Node.py 2 compatible with it?

**Comment by rsodre** [comment]
Nodepy2 installed. Now this...

```
$ nodepy --version
nodepy 2.0.0
[cpython 2.7.14 (default, Oct  2 2017, 21:42:22) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]]

$ nodepy https://raw.githubusercontent.com/nodepy/nodepy-pm/master/scripts/install-remote.py
fatal: no tags look like versions, try adding a Git ref to
       the command (eg. master).
```

**Comment by NiklasRosenstein** [comment]
Oh right, sorry. I always forget it myself. The `nodepy-pm` repository is not tagged yet, so you need to specify the Git ref explicitly.

    $ nodepy https://raw.githubusercontent.com/nodepy/nodepy-pm/master/scripts/install-remote.py master

> I'm installing for c4ddev. Is Node.py 2 compatible with it?

Ah, good that you're saying it. C4ddev is not updated yet. So you'll need to stick with the previous version (`pip install node.py`). You won't need the extra step of installing the package manager when using the old version, it already installs it (and the package manager is called `nppm` there).

**Comment by NiklasRosenstein** [comment]
I'll update C4ddev for Node.py 2 soon, but the C4ddev C4D plugins rely on Node.py being a single-file module to build a standalone-distributable, but that is no longer the case with Node.py 2.

**Comment by rsodre** [comment]
Ok, but I've been trying to install and run nodepy-pm/nppm this way the whole day but never suceded.

When I do `pip install node.py` it always says I already have everything installed (no mention of nppm)...

```
$ sudo pip install node.py
The directory '/Users/roger/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/roger/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: node.py in /usr/local/lib/python2.7/site-packages
Requirement already satisfied: colorama>=0.3.9 in /Users/roger/Library/Python/2.7/lib/python/site-packages (from node.py)
Requirement already satisfied: localimport>=1.5.1 in /Users/roger/Library/Python/2.7/lib/python/site-packages (from node.py)
Requirement already satisfied: six>=1.10.0 in /Users/roger/Library/Python/2.7/lib/python/site-packages (from node.py)
Requirement already satisfied: pip>=8.0.0 in /Users/roger/Library/Python/2.7/lib/python/site-packages (from node.py)
Requirement already satisfied: wheel>=0.29.0 in /Users/roger/Library/Python/2.7/lib/python/site-packages (from node.py)
```

When I do `pip install node.py --ignore-installed`, I can see it's installing nppm, bt will not finish [because of this](https://github.com/nodepy/nodepy/issues/71)...

$ sudo pip install node.py --ignore-installed
The directory '/Users/roger/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/roger/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting node.py
  Downloading node.py-0.0.22.tar.gz (59kB)
    100% |████████████████████████████████| 61kB 247kB/s 
Collecting colorama>=0.3.9 (from node.py)
  Downloading colorama-0.3.9-py2.py3-none-any.whl
Collecting localimport>=1.5.1 (from node.py)
Collecting six>=1.10.0 (from node.py)
  Downloading six-1.11.0-py2.py3-none-any.whl
Collecting pip>=8.0.0 (from node.py)
  Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 371kB/s 
Collecting wheel>=0.29.0 (from node.py)
  Downloading wheel-0.30.0-py2.py3-none-any.whl (49kB)
    100% |████████████████████████████████| 51kB 719kB/s 
Installing collected packages: colorama, localimport, six, pip, wheel, node.py
  Running setup.py install for node.py ... error
    Complete output from command /usr/local/opt/python/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-VzzSgb/node.py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-Vi6S4X-record/install-record.txt --single-version-externally-managed --compile:
    running install
    Installing Node.py and Node.py-PM dependencies in a separate context ...
      Command: pip install colorama>=0.3.9 localimport>=1.5.1 six>=1.10.0 pip>=8.0.0 wheel>=0.29.0
    The directory '/Users/roger/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    The directory '/Users/roger/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    Requirement already satisfied: colorama>=0.3.9 in /Users/roger/Library/Python/2.7/lib/python/site-packages
    Requirement already satisfied: localimport>=1.5.1 in /Users/roger/Library/Python/2.7/lib/python/site-packages
    Requirement already satisfied: six>=1.10.0 in /Users/roger/Library/Python/2.7/lib/python/site-packages
    Requirement already satisfied: pip>=8.0.0 in /Users/roger/Library/Python/2.7/lib/python/site-packages
    Requirement already satisfied: wheel>=0.29.0 in /Users/roger/Library/Python/2.7/lib/python/site-packages
    running build
    running build_py
    creating build
    creating build/lib
    copying nodepy.py -> build/lib
    running install_lib
    running install_egg_info
    running egg_info
    writing requirements to node.py.egg-info/requires.txt
    writing node.py.egg-info/PKG-INFO
    writing top-level names to node.py.egg-info/top_level.txt
    writing dependency_links to node.py.egg-info/dependency_links.txt
    writing entry points to node.py.egg-info/entry_points.txt
    reading manifest file 'node.py.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    no previously-included directories found matching 'nppm/dist'
    no previously-included directories found matching 'nppm/nodepy_modules'
    writing manifest file 'node.py.egg-info/SOURCES.txt'
    removing '/usr/local/lib/python2.7/site-packages/node.py-0.0.22-py2.7.egg-info' (and everything under it)
    Copying node.py.egg-info to /usr/local/lib/python2.7/site-packages/node.py-0.0.22-py2.7.egg-info
    running install_scripts
    Installing nodepy2 script to /usr/local/bin
    Installing nodepy script to /usr/local/bin
    Installing nodepy2.7 script to /usr/local/bin
    writing list of installed files to '/tmp/pip-Vi6S4X-record/install-record.txt'
    Bootstrapping NPPM dependencies with Pip ...
    ('$ pip install', u'--target nodepy_modules/.pip/lib/python2.7/site-packages distlib>=0.2.4 hammock>=0.2.4 jsonschema>=2.6.0 requests>=2.13.0 click>=6.7 appdirs>=1.4.2')
    Note: macOS detected, applying homebrew fix (see nodepy/ppym#9)
          [install] prefix=
    The directory '/Users/roger/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    The directory '/Users/roger/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    Collecting distlib>=0.2.4
    Collecting hammock>=0.2.4
    Collecting jsonschema>=2.6.0
      Downloading jsonschema-2.6.0-py2.py3-none-any.whl
    Collecting requests>=2.13.0
      Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)
    Collecting click>=6.7
      Downloading click-6.7-py2.py3-none-any.whl (71kB)
    Collecting appdirs>=1.4.2
      Downloading appdirs-1.4.3-py2.py3-none-any.whl
    Collecting functools32; python_version == "2.7" (from jsonschema>=2.6.0)
    Collecting idna<2.7,>=2.5 (from requests>=2.13.0)
      Downloading idna-2.6-py2.py3-none-any.whl (56kB)
    Collecting urllib3<1.23,>=1.21.1 (from requests>=2.13.0)
      Downloading urllib3-1.22-py2.py3-none-any.whl (132kB)
    Collecting certifi>=2017.4.17 (from requests>=2.13.0)
      Downloading certifi-2017.11.5-py2.py3-none-any.whl (330kB)
    Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.13.0)
      Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)
    Installing collected packages: distlib, idna, urllib3, certifi, chardet, requests, hammock, functools32, jsonschema, click, appdirs
    Successfully installed appdirs-1.4.3 certifi-2017.11.5 chardet-3.0.4 click-6.7 distlib-0.2.6 functools32-3.2.3.post2 hammock-0.2.4 idna-2.6 jsonschema-2.6.0 requests-2.18.4 urllib3-1.22
    Installing NPPM (install --ignore-installed --upgrade --root /private/tmp/pip-build-VzzSgb/node.py/nppm --pip-separate-process) ...
    Installing "@nodepy/nppm@0.0.22"...
    Installing Python dependencies for "@nodepy/nppm@0.0.22"...
      Installing Python dependencies via Pip: distlib>=0.2.4 hammock>=0.2.4 jsonschema>=2.6.0 requests>=2.13.0 click>=6.7 appdirs>=1.4.2 --ignore-installed --upgrade (as a separate process)
    Note: macOS detected, applying homebrew fix (see nodepy/ppym#9)
          [install] prefix=
    The directory '/Users/roger/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    The directory '/Users/roger/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    Collecting distlib>=0.2.4
    Collecting hammock>=0.2.4
    Collecting jsonschema>=2.6.0
      Downloading jsonschema-2.6.0-py2.py3-none-any.whl
    Collecting requests>=2.13.0
      Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)
    Collecting click>=6.7
      Downloading click-6.7-py2.py3-none-any.whl (71kB)
    Collecting appdirs>=1.4.2
      Downloading appdirs-1.4.3-py2.py3-none-any.whl
    Collecting functools32; python_version == "2.7" (from jsonschema>=2.6.0)
    Collecting idna<2.7,>=2.5 (from requests>=2.13.0)
      Downloading idna-2.6-py2.py3-none-any.whl (56kB)
    Collecting urllib3<1.23,>=1.21.1 (from requests>=2.13.0)
      Downloading urllib3-1.22-py2.py3-none-any.whl (132kB)
    Collecting certifi>=2017.4.17 (from requests>=2.13.0)
      Downloading certifi-2017.11.5-py2.py3-none-any.whl (330kB)
    Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.13.0)
      Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)
    Installing collected packages: distlib, idna, urllib3, certifi, chardet, requests, hammock, functools32, jsonschema, click, appdirs
    Exception:
    Traceback (most recent call last):
      File "/Users/roger/Library/Python/2.7/lib/python/site-packages/pip/basecommand.py", line 215, in main
        status = self.run(options, args)
      File "/Users/roger/Library/Python/2.7/lib/python/site-packages/pip/commands/install.py", line 342, in run
        prefix=options.prefix_path,
      File "/Users/roger/Library/Python/2.7/lib/python/site-packages/pip/req/req_set.py", line 784, in install
        **kwargs
      File "/Users/roger/Library/Python/2.7/lib/python/site-packages/pip/req/req_install.py", line 851, in install
        self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
      File "/Users/roger/Library/Python/2.7/lib/python/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
        isolated=self.isolated,
      File "/Users/roger/Library/Python/2.7/lib/python/site-packages/pip/wheel.py", line 492, in move_wheel_files
        maker.make_multiple(['%s = %s' % kv for kv in console.items()])
      File "/Users/roger/Library/Python/2.7/lib/python/site-packages/pip/_vendor/distlib/scripts.py", line 383, in make_multiple
        filenames.extend(self.make(specification, options))
      File "/Users/roger/Library/Python/2.7/lib/python/site-packages/pip/_vendor/distlib/scripts.py", line 372, in make
        self._make_script(entry, filenames, options=options)
      File "/Users/roger/Library/Python/2.7/lib/python/site-packages/pip/_vendor/distlib/scripts.py", line 276, in _make_script
        self._write_script(scriptnames, shebang, script, filenames, ext)
      File "/Users/roger/Library/Python/2.7/lib/python/site-packages/pip/_vendor/distlib/scripts.py", line 250, in _write_script
        self._fileop.write_binary_file(outname, script_bytes)
      File "/Users/roger/Library/Python/2.7/lib/python/site-packages/pip/_vendor/distlib/util.py", line 407, in write_binary_file
        with open(path, 'wb') as f:
    IOError: [Errno 1] Operation not permitted: '/bin/chardetect'
    Error: `pip install` failed with exit-code 2
    Error: Installation failed
    
    ----------------------------------------
Command "/usr/local/opt/python/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-VzzSgb/node.py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-Vi6S4X-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-VzzSgb/node.py/

```

When I do `pip install node.py --ignore-installed --user`,installation completes, but don't look like it installed nppm:

```
$ sudo pip install node.py --ignore-installed --user
The directory '/Users/roger/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/roger/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting node.py
  Downloading node.py-0.0.22.tar.gz (59kB)
    100% |████████████████████████████████| 61kB 447kB/s 
Collecting colorama>=0.3.9 (from node.py)
  Downloading colorama-0.3.9-py2.py3-none-any.whl
Collecting localimport>=1.5.1 (from node.py)
Collecting six>=1.10.0 (from node.py)
  Downloading six-1.11.0-py2.py3-none-any.whl
Collecting pip>=8.0.0 (from node.py)
  Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 374kB/s 
Collecting wheel>=0.29.0 (from node.py)
  Downloading wheel-0.30.0-py2.py3-none-any.whl (49kB)
    100% |████████████████████████████████| 51kB 714kB/s 
Installing collected packages: colorama, localimport, six, pip, wheel, node.py
  Running setup.py install for node.py ... done
Successfully installed colorama-0.3.9 localimport-1.5.2 node.py-0.0.22 pip-9.0.1 six-1.11.0 wheel-0.30.0

$ which nodepy
/usr/local/bin/nodepy

$ nodepy
Node.py-0.0.22 [cpython 2.7.14 64-bit]
>>> 

$ nppm
-bash: nppm: command not found

$ ls -l /usr/local/bin/n*
-rwxr-xr-x  1 root  admin  402 Nov 24 14:25 /usr/local/bin/nodepy
-rwxr-xr-x  1 root  admin  404 Nov 24 14:25 /usr/local/bin/nodepy2
-rwxr-xr-x  1 root  admin  408 Nov 24 14:25 /usr/local/bin/nodepy2.7

```

**Comment by NiklasRosenstein** [comment]
Looks a lot like https://github.com/nodepy/nodepy/issues/71#issuecomment-341875374. It seems you've already seen this comment, did following the same commands not fix the problem?

```
$ sudo pip uninstall node.py
$ sudo pip uninstall wheel
$ sudo pip uninstall chardet
$ pip install --user node.py
```

On a side note, when the installation suceeds, you may need to add `~/.local/bin` to your `PATH` environment variable (not sure if it's in there by default on OSX).

**Comment by rsodre** [comment]
ok, now it's working!
I didn't have my user bin in the path, that's why I could not run nppm.

```
BREW_PREFIX=`brew --prefix`
export PATH=$HOME/Library/Python/2.7/bin:$BREW_PREFIX/share/python:$BREW_PREFIX/bin:$BREW_PREFIX/sbin:$PATH
export PYTHONPATH=$BREW_PREFIX/lib/python2.7/site-packages:$PYTHONPATH
export PYTHONPATH=/Library/Python/2.7/site-packages:$PYTHONPATH
```

Now I can continue with c4ddev, but nppm does not find it. Did your repo moved?
(shall we move this discussion somewhere else, since it's now related to c4ddev?)

```
$ nppm install c4ddev
...
  File "/Users/roger/Library/Python/2.7/lib/python/nodepy_modules/@nodepy/nppm/lib/registry.py", line 147, in _handle_response
    raise Error(response, "Invalid JSON returned")
Error: Invalid JSON returned
  Url:  https://www.niklasrosenstein.com/api/find/c4ddev/* -- Status 404
  Body: <html>
<head><title>404 Not Found</titl...enter>nginx</center>
</body>
</html>

$ nppm install @NiklasRosenstein/c4ddev
...
  File "/Users/roger/Library/Python/2.7/lib/python/nodepy_modules/@nodepy/nppm/lib/registry.py", line 147, in _handle_response
    raise Error(response, "Invalid JSON returned")
Error: Invalid JSON returned
  Url:  https://www.niklasrosenstein.com/api/find/@NiklasRosenstein/c4ddev/* -- Status 404
  Body: <html>
<head><title>404 Not Found</titl...enter>nginx</center>
</body>
</html>

```

**Comment by NiklasRosenstein** [comment]
Great!

> Now I can continue with c4ddev, but nppm does not find it. Did your repo moved?

No, but https://registry.nodepy.org/ is down, and it won't be up again until I'll update the registry server for Node.py 2. You can simply install from the Git repository instead.

    $ nppm install git+https://github.com/NiklasRosenstein/c4ddev.git

> (shall we move this discussion somewhere else, since it's now related to c4ddev?)

Nah, it's fine, no need to create a separate issue on the c4ddev repo. This is still related to Node.py in a way.

**Comment by rsodre** [comment]
It still needs more stuff from registry.
Better just wait until it gets back online then.
Thanks Niklas!

**Comment by NiklasRosenstein** [comment]
Right, sorry about that. I've just updated the command-line tools for Node.py 2. Note that you should not use that development version for use as Cinema 4D plugin, the plugin part still needs to be updated.

```
$ pip uninstall node.py 
$ pip install nodepy-runtime --user
$ nodepy https://nodepy.org/install-pm.py master --upgrade --global
$ nodepy-pm install https://github.com/NiklasRosenstein/c4ddev.git@develop --global
```

Also note that the `c4ddev build-loader` command will not work at the time.

**Comment by rsodre** [comment]
Hi! Ok, for install-pm.py I had to install some missing dependencies manually:

```
pip install click
pip install nr
pip install hammock
```

For c4ddev, I had to use the slightly different command found on the develop branch readme, and it failed to install.

```
$ sudo nodepy-pm install git+https://github.com/NiklasRosenstein/c4ddev.git@develop --global
Note: implying --internal due to --global.
Cloning repository: $ ['git', 'clone', u'https://github.com/NiklasRosenstein/c4ddev.git', '/Users/roger/Library/Python/2.7/lib/python/nodepy-modules/.tmp', '-b', u'develop']
Cloning into '/Users/roger/Library/Python/2.7/lib/python/nodepy-modules/.tmp'...
remote: Counting objects: 1753, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 1753 (delta 1), reused 5 (delta 1), pack-reused 1746
Receiving objects: 100% (1753/1753), 1.60 MiB | 208.00 KiB/s, done.
Resolving deltas: 100% (938/938), done.
Installing "@NiklasRosenstein/c4ddev@0.1.6"...
Installing Python dependencies for "@NiklasRosenstein/c4ddev@0.1.6"...
  Installing Python dependencies via Pip: --prefix /Users/roger/Library/Python/2.7/lib/python/nodepy-modules/@NiklasRosenstein/c4ddev/.nodepy/pip bs4 nr>=1.4.3 click>=6.7 
Note: macOS detected, applying homebrew fix (see nodepy/ppym#9)
      [install] prefix=
The directory '/Users/roger/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/roger/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting bs4
  Downloading bs4-0.0.1.tar.gz
Requirement already satisfied: nr>=1.4.3 in /usr/local/lib/python2.7/site-packages
Requirement already satisfied: click>=6.7 in /usr/local/lib/python2.7/site-packages
Collecting beautifulsoup4 (from bs4)
  Downloading beautifulsoup4-4.6.0-py2-none-any.whl (86kB)
    100% |████████████████████████████████| 92kB 312kB/s 
Installing collected packages: beautifulsoup4, bs4
  Running setup.py install for bs4 ... done
Successfully installed beautifulsoup4-4.6.0 bs4-0.0.1
Moving "@NiklasRosenstein/c4ddev@0.1.6" to "/Users/roger/Library/Python/2.7/lib/python/nodepy-modules/@NiklasRosenstein/c4ddev" ...
True
Traceback (most recent call last):
  File "/Users/roger/Library/Python/2.7/bin/nodepy-pm", line 10, in <module>
    sys.exit(nodepy.main.main())
  File "/Users/roger/Library/Python/2.7/lib/python/site-packages/nodepy/main.py", line 113, in main
    ctx.load_module(ctx.main_module, do_init=False)
  File "/Users/roger/Library/Python/2.7/lib/python/site-packages/nodepy/context.py", line 329, in load_module
    module.load()
  File "/Users/roger/Library/Python/2.7/lib/python/site-packages/nodepy/loader.py", line 41, in load
    exec(code, vars(self.namespace))
  File "/Users/roger/Library/Python/2.7/lib/python/nodepy-modules/nodepy-pm/index.py", line 570, in <module>
    main()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/roger/Library/Python/2.7/lib/python/nodepy-modules/nodepy-pm/index.py", line 109, in wrapper
    res = func(*args, **kwargs)
  File "/Users/roger/Library/Python/2.7/lib/python/nodepy-modules/nodepy-pm/index.py", line 293, in install
    success, info = installer.install_from_requirement(req)
  File "/Users/roger/Library/Python/2.7/lib/python/nodepy-modules/nodepy-pm/lib/install.py", line 481, in install_from_requirement
    return self.install_from_git(req.git_url, req.recursive, internal=req.internal, pure=req.pure)
  File "/Users/roger/Library/Python/2.7/lib/python/nodepy-modules/nodepy-pm/lib/install.py", line 753, in install_from_git
    internal=internal, pure=pure)
  File "/Users/roger/Library/Python/2.7/lib/python/nodepy-modules/nodepy-pm/lib/util/decorators.py", line 35, in wrapper
    return func(*args, **kwargs)
  File "/Users/roger/Library/Python/2.7/lib/python/nodepy-modules/nodepy-pm/lib/install.py", line 599, in install_from_directory
    os.rename(directory, target_dir)
OSError: [Errno 66] Directory not empty
```

**Comment by NiklasRosenstein** [comment]
Hi @rsodre , thanks for sticking to this. You're right, I forgot to add the `git+` prefix to the last command in my previous command.

> Hi! Ok, for install-pm.py I had to install some missing dependencies manually:

Hm, they should've been installed automatically. :/ Do you still have the log from the nodepy-pm installation that failed because of missing dependencies?

> For c4ddev, I had to use the slightly different command found on the develop branch readme, and it failed to install.

Please try again, this broke just recently and I just pushed a fixed (https://github.com/nodepy/nodepy-pm/commit/f36461a032ff5f0fa60cd38599aeec5e760d1cd8)

**Comment by rsodre** [comment]
Awesome! I've got c4ddev now, thanks!

> Do you still have the log from the nodepy-pm installation that failed because of missing dependencies?

Only the console, here: [](https://pastebin.com/WdMw2wpF)
Is there any other logs that I can find for you?

**Comment by NiklasRosenstein** [comment]
Thanks, that's exactly what I meant!

If all works correctly, you shouldn't need to install click or nr manually. But I think I know where this error is coming from. I'll investigate this in a separate issue.

By the way, you should only use sudo when installing nodepy-pm itself (which defaults to using `--root`) or when installing with the `--root` flag. In any other case, the install location will be something your current user always has access to anyway.

That last part confuses me a bit, as it seems you've got a version of nodepy-pm *before* https://github.com/nodepy/nodepy-pm/commit/f36461a032ff5f0fa60cd38599aeec5e760d1cd8 because the `OSError` still occurred.

Anyway, I just tagged a v2.0.0 for nodepy-pm, so in the future you should be able to skip the `master` argument and it will install the newest tagged version.

    $ sudo nodepy https://nodepy.org/install-pm.py
    downloading zipball for "v2.0.0"...
    [...]
